### ISSUE TITLE
Could you rename class and do some enhancements?

### ISSUE THREAD

**Issue by CGevorg** [ShadowZ1xy/clean-your-folder#3]
https://github.com/ShadowZ1xy/clean-your-folder/blob/035743caa3d531c007d420590ec653dc23e0c21c/src/dir/cleaner/MyFile.java#L6

Could you rename a file? <br>
It seems that it is a utility class could you move it to the new 'util' package? <br> 
Review the accessibilities of your functions.

**Comment by ShadowZ1xy** [comment]
Okay, fixed in 6ed4f7858d93706dd7ce21375c79eeadfc9594c9 commit
