### ISSUE TITLE
Encapsulate selected fields.

### ISSUE THREAD

**Issue by CGevorg** [ShadowZ1xy/clean-your-folder#4]
https://github.com/ShadowZ1xy/clean-your-folder/blob/c8d157b42c4de230a8c20cdfbfdd7b0e8ad31bbe/src/dir/cleaner/data/Data.java#L9
https://github.com/ShadowZ1xy/clean-your-folder/blob/c8d157b42c4de230a8c20cdfbfdd7b0e8ad31bbe/src/dir/cleaner/data/Data.java#L10

**Comment by ShadowZ1xy** [comment]
thanks for the feedback, fixed on 71b739e4c81d8c6f19d50306813c4f3eb8708a9d
